sonar.projectKey=launchpad
sonar.projectName=LaunchPad
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.test.tsx
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
